// Code generated by entc, DO NOT EDIT.

package pet

import (
	"github.com/kidlj/demo/ent/mixins/ent/schema"
)

const (
	// Label holds the string label denoting the pet type in the database.
	Label = "pet"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAge holds the string denoting the age vertex property in the database.
	FieldAge = "age"
	// FieldName holds the string denoting the name vertex property in the database.
	FieldName = "name"
	// FieldWeight holds the string denoting the weight vertex property in the database.
	FieldWeight = "weight"

	// Table holds the table name of the pet in the database.
	Table = "pets"
)

// Columns holds all SQL columns are pet fields.
var Columns = []string{
	FieldID,
	FieldAge,
	FieldName,
	FieldWeight,
}

var (
	fields = schema.Pet{}.Fields()

	// descAge is the schema descriptor for age field.
	descAge = mixinFields[0][0].Descriptor()
	// AgeValidator is a validator for the "age" field. It is called by the builders before save.
	AgeValidator = descAge.Validators[0].(func(int) error)

	// descName is the schema descriptor for name field.
	descName = mixinFields[0][1].Descriptor()
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator = descName.Validators[0].(func(string) error)
)
